### ISSUE TITLE
GPU names in the list?

### ISSUE THREAD

**Issue by karolmajek** [run-ai/rntop#1]
Is there any option to get GPU names in the list?
not those short names from default `nvidia-smi` view, but longer versions from `nvidia-smi -L` (e.g. there are 3+ Titan cards `TITAN X (Pascal)` vs `GeForce GTX TITAN X` which short is `GeForce GTX TIT...`)

**Comment by rotenbergrr** [comment]
hi @karolmajek and thanks a lot for this feedback!
this is a great feature suggestion.
we released version [0.1.2](https://github.com/run-ai/rntop/releases/tag/v0.1.2) of `rntop` which includes what you suggested.
to use it please pass the argument `--gpu-name` in the command line.
make sure to pull the [newest Docker image](https://hub.docker.com/layers/rntop/runai/rntop/latest/images/sha256-c58a61ed05f5a52d0c82de565f16d46ec6520aa442671068350bbacfa57bdcca?context=repo) tag by running `docker pull runai/rntop` before.
thanks again for the feedback and we are waiting to hear more from you!
