### ISSUE TITLE
Feature request: Adding GPU temperature monitoring

### ISSUE THREAD

**Issue by JunweiLiang** [run-ai/rntop#10]
Hi! 

Thanks for the great work. Could you consider adding GPU temperature monitoring in the tool, which is helpful information to monitor machine health?

Thanks!

**Comment by rotenbergrr** [comment]
hey @JunweiLiang, 
first of all thanks for reaching out and sorry for the late response.

thank you for this feature request, it sounds like a good addition to rntop.
however, our roadmap is to migrate rntop capabilities into our other open-source project [Genv](https://github.com/run-ai/genv).
to be clear, at the moment we don't have GPU temperature monitoring in Genv, but we can add it in the future to Genv's monitoring capabilities.

**Comment by rotenbergrr** [comment]
hey @JunweiLiang, thanks again for reaching out originally.

we just finished migrating rntop monitoring capabilities into Genv remote monitoring.
this is part of the latest release of Genv which is 1.3.0.

you can find the documentation and tutorials here: https://docs.genv.dev/remote/monitoring.html

I also added the GPU temperature metric as you asked and updated the Grafana dashboard to show it so it looks like this:
![image](https://github.com/run-ai/rntop/assets/24877320/6f2dd03d-387f-4a07-9693-5db3bf58d4df)

I'm closing the issue but would love to continue chatting, please share if you found this useful and if it answers your needs.
