### ISSUE TITLE
Memory in GB instead of MB

### ISSUE THREAD

**Issue by karolmajek** [run-ai/rntop#2]
feature request
a way to switch to GB - a more human readable form

**Comment by rotenbergrr** [comment]
hi @karolmajek and thanks a lot for this feedback!
this is a great feature suggestion.
we released version [0.1.2](https://github.com/run-ai/rntop/releases/tag/v0.1.2) of `rntop` which includes what you suggested.
to use it please pass the argument `--gb` in the command line.
make sure to pull the [newest Docker image](https://hub.docker.com/layers/rntop/runai/rntop/latest/images/sha256-c58a61ed05f5a52d0c82de565f16d46ec6520aa442671068350bbacfa57bdcca?context=repo) tag by running `docker pull runai/rntop` before.
thanks again for the feedback and we are waiting to hear more from you!
